// Paste values from Supabase: Project Settings -> API.
window.YCLOUD_SUPABASE_URL = 'REPLACE_WITH_YOUR_SUPABASE_PROJECT_URL';
window.YCLOUD_SUPABASE_ANON_KEY = 'REPLACE_WITH_YOUR_SUPABASE_ANON_KEY';
